# permissions for end users to view affinities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: affinity-viewer-role
rules:
- apiGroups:
  - rule.newbis.top
  resources:
  - affinities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rule.newbis.top
  resources:
  - affinities/status
  verbs:
  - get
