
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rule.newbis.top
  resources:
  - affinities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rule.newbis.top
  resources:
  - affinities/status
  verbs:
  - get
  - patch
  - update
